# Generated by Django 4.2.1 on 2023-05-19 19:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('weight', models.IntegerField(default=1)),
                ('code', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]*$', 'Allowed only upper case letters, underscore and numbers')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='picturecase/', verbose_name='PictureCase')),
            ],
            options={
                'verbose_name_plural': 'Medicationes',
            },
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('serial_number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('model', models.CharField(choices=[('Lightweight', 'Lightweight'), ('Middleweight', 'Middleweight'), ('Cruiserweight', 'Cruiserweight'), ('Heavyweight', 'Heavyweight')], default='Lightweight', max_length=15)),
                ('weight_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('battery_capacity', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('IDLE', 'IDLE'), ('LOADING', 'LOADING'), ('LOADED', 'LOADED'), ('DELIVERING', 'DELIVERED'), ('RETURNING', 'RETURNING')], default='IDLE', max_length=10)),
                ('medicationes', models.ManyToManyField(to='drones.medication')),
            ],
            options={
                'verbose_name_plural': 'Drones',
            },
        ),
    ]
